#config_version=6

# Bumpers start with a value of 210 points.
# Every 30 hits, the value per hit is increased by an additional 500 points (global_pf_multiplier)


shots:
  bumper_left_shot:
    switch: s_bumper_left
  bumper_right_shot:
    switch: s_bumper_right
  bumper_bottom_shot:
    switch: s_bumper_bottom

shot_groups:
  bumpers_shots:
    shots: bumper_left_shot, bumper_right_shot, bumper_bottom_shot

slide_player:
  start_base_bumpers: bumpers
  bumpers_shots_hit:
    bumpers:
      action: method
      method: top_down_text
  stop_base_bumpers:
    bumpers:
      action: remove

variable_player:
  mode_base_started{not is_extra_ball}:
    bumpers_score:
      int: 210
      action: set
  bumpers_shots_hit:
    score: current_player.bumpers_score * current_player.pf_multiplier

show_player:
  bumper_left_shot_hit:
    flashing_show:
      loops: 0
      speed: 8
      show_tokens:
        led: led_bumper_left
        color: green
  bumper_right_shot_hit:
    flashing_show:
      loops: 0
      speed: 8
      show_tokens:
        led: led_bumper_right
        color: green
  bumper_bottom_shot_hit:
    flashing_show:
      loops: 0
      speed: 8
      show_tokens:
        led: led_bumper_right
        color: green