#config_version=6

slide_player:
  priority: 1_000
  start_base_log: log
  stop_base_log:
    log:
      action: remove
  skill_failed:
    log:
      action: method
      method: log_text
      tokens:
        text: "skill failed"
  skill_success:
    log:
      action: method
      method: log_text
      tokens:
        text: "skill success"
  super_skill_success:
    log:
      action: method
      method: log_text
      tokens:
        text: "Super skill success"
#  auto_launch_plunger:
#    log:
#      action: method
#      method: log_text
#      tokens:
#        text: "Auto launch"
  shot_ramps_combo_hit:
    log:
      action: method
      method: log_text
      tokens:
        text: "Ramps Combo !"
  bm_lanes_lit_complete:
    log:
      action: method
      method: log_text
      tokens:
        text: "Bonus increased"
  super_bumpers_restart:
    log:
      action: method
      method: log_text
      tokens:
        text: "Super Bumpers"
  pf_multiplier_start:
    log:
      action: method
      method: log_text
      tokens:
        text: "Pf multiplier flashing"
  logicblock_zodiac_sequence_hit{step==1}:
    log:
      action: method
      method: log_text
      tokens:
        text: "Zodiac"
  logicblock_zodiac_sequence_hit{step==2}:
    log:
      action: method
      method: log_text
      tokens:
        text: "ZOdiac"
  logicblock_zodiac_sequence_hit{step==3}:
    log:
      action: method
      method: log_text
      tokens:
        text: "ZODiac"
  logicblock_zodiac_sequence_hit{step==4}:
    log:
      action: method
      method: log_text
      tokens:
        text: "ZODIac"
  logicblock_zodiac_sequence_hit{step==5}:
    log:
      action: method
      method: log_text
      tokens:
        text: "ZODIAc"
  logicblock_zodiac_sequence_hit{step==6}:
    log:
      action: method
      method: log_text
      tokens:
        text: "ZODIAC"
  zodiac_validation_shot_hit:
    log:
      action: method
      method: log_text
      tokens:
        text: "ZODIAC !!!"
  zodiac_extraball_shot_is_lit:
    log:
      action: method
      method: log_text
      tokens:
        text: "Zodiac extraball is lit"
  gold_knights_extraballs_shot_is_lit:
    log:
      action: method
      method: log_text
      tokens:
        text: "GK extraball is lit"
  extra_ball_awarded:
    log:
      action: method
      method: log_text
      tokens:
        text: "EXTRABALL !"
  stop_mode_gold_knight_1:
    log:
      action: method
      method: log_text
      tokens:
        text: "stop mode gold knight 1"
  logicblock_leos_hits_counter_hit:
    log:
      action: method
      method: log_text
      tokens:
        text: "Orbit"
  ikki_lock_enabled:
    log:
      action: method
      method: log_text
      tokens:
        text: "Lock is lit"
  ikki_dummy_lock_enabled:
    log:
      action: method
      method: log_text
      tokens:
        text: "Lock is lit"
  ikki_locked:
    log:
      action: method
      method: log_text
      tokens:
        text: "Ball locked"
  ikki_dummy_locked:
    log:
      action: method
      method: log_text
      tokens:
        text: "Ball locked"
  multiball_ikki_multiball_started:
    log:
      action: method
      method: log_text
      tokens:
        text: "IKKI MULTIBALL !"
