#config_version=6


shots:
  gold_knights_extraballs_shot:
    switch: s_scoop
    profile: quick_flashing_profile
    enable_events: gold_knights_extraballs_shot_is_lit
    disable_events: gold_knights_extraballs_shot_flashing_hit
    restart_events: gold_knights_extraballs_shot_flashing_hit
    show_tokens:
      led: led_scoop_extraball
      color: FF0000
  zodiac_extraball_shot:
    switch: s_kickout
    profile: quick_flashing_profile
    enable_events: zodiac_extraball_shot_is_lit
    disable_events: zodiac_extraball_shot_flashing_hit
    restart_events: zodiac_extraball_shot_flashing_hit
    show_tokens:
      led: led_kickout_extraball
      color: FF0000


extra_balls:
  gold_knight_extraball:
    max_per_game: 100
    award_events: gold_knights_extraballs_shot_flashing_hit
  zodiac_ramps_extraball:
    award_events: zodiac_extraball_shot_flashing_hit


light_player:
  extra_ball_awarded:
    led_ballsave: yellow
  mode_base_started{current_player.extra_balls > 0}:
    led_ballsave: yellow


sequences:
  gold_knights_extraballs_sequence:
    events:
      - gold_knights_extraballs_is_lit
      - mode_gold_knight_stopped, mode_base_started
    persist_state: true
    disable_on_complete: false
    events_when_complete: gold_knights_extraballs_shot_is_lit

event_player:
  mode_gold_knight_started{current_player.knights_confronted_total_count % 3 == 0}: gold_knights_extraballs_is_lit
  zodiac_validation_shot_flashing_hit{current_player.zodiac_total_count == 3}: zodiac_extraball_shot_is_lit
