#config_version=6

# Hitting the top two lanes on top of the bumpers and the inner 2 lanes will increase the bonus multiplier.
# The bonus multiplier can be increased up to 5x.

mode:
  start_events: start_mode_bonus_multiplier
  stop_events: stop_mode_bonus_multiplier
  priority: 110

shots:
  inlane_left:
    switch: s_inlane_left
    show_tokens:
      led: led_inlane_left
      color: 0000FF
  inlane_right:
    switch: s_inlane_right
    show_tokens:
      led: led_inlane_right
      color: 0000FF
  dragon_lane_left:
    switch: s_dragon_lane_left
    show_tokens:
      led: led_dragon_lane_left
      color: 0000FF
  dragon_lane_right:
    switch: s_dragon_lane_right
    show_tokens:
      led: led_dragon_lane_right
      color: 0000FF

shot_profiles:
  lanes_profile:
    states:
      - name: unlit
        show: off
      - name: lit
        show: on
    loop: true

shot_groups:
  bm_lanes:
    shots: inlane_left, inlane_right, dragon_lane_left, dragon_lane_right
    reset_events:
      bm_lanes_lit_complete: 1s

variable_player:
  bm_lanes_lit_complete{current_player.bonus_multiplier<5}:
    bonus_multiplier: 1
  bm_lanes_lit_complete:
    score: 100_000 * current_player.pf_multiplier
