#config_version=6

# 5. Aioria de leo = Super Loops
# In this mode the top gates are open to allow full orbit loops.
# Completing a full loop scores 140,000.
# Get 4 shots and undo Aioria's spell

mode:
  start_events: start_mode_gold_knight_5
  stop_events: stop_mode_gold_knight, stop_missions
  events_when_started: mode_type_mission_started, mode_gold_knight_started
  events_when_stopped: mode_type_mission_stopped, mode_gold_knight_stopped
  priority: 400

sequence_shots:
  leo_left_orbit:
    switch_sequence: s_orbit_left, s_orbit_right
    sequence_timeout: 3s
  leo_right_orbit:
    switch_sequence: s_orbit_right, s_orbit_left
    sequence_timeout: 3s

counters:
  leo_orbits_hits_counter:
    starting_count: 4
    count_complete_value: 0
    direction: down
    count_events: leo_left_orbit_hit, leo_right_orbit_hit
    events_when_complete: stop_mode_gold_knight

variable_player:
  logicblock_leo_orbits_hits_counter_hit:
    score: 140_000 * current_player.pf_multiplier


show_player:
  mode_gold_knight_5_started:
    flashing_show:
      show_tokens:
        led: led_gold_knight_5
        color: ffffff
    flashing_show_bis:
      speed: 5
      show_tokens:
        led: led_orbit_left, led_orbit_right
        color: yellow
