#config_version=6

# 2. ALDEBARAN OF TAURUS = ORBITS
# The left and right orbits score points during this mode.
# Collect 280,000 points (4 orbits) to complete the mode.

mode:
  start_events: start_mode_gold_knight_2
  stop_events: stop_mode_gold_knight_2, stop_missions
  events_when_started: mode_type_mission_started, mode_gold_knight_started
  events_when_stopped: mode_type_mission_stopped, mode_gold_knight_stopped
  priority: 400

shots:
  taurus_left_orbit:
    switch: s_orbit_left
    profile: flashing_profile
    show_tokens:
      led: led_orbit_left
      color: ffffff
  taurus_right_orbit:
    switch: s_orbit_right
    profile: flashing_profile
    show_tokens:
      led: led_orbit_right
      color: ffffff

shot_groups:
  taurus_orbits:
    shots: taurus_left_orbit, taurus_right_orbit

counters:
  taurus_orbits_hits_counter:
    starting_count: 4
    count_complete_value: 0
    direction: down
    count_events: taurus_orbits_flashing_hit

variable_player:
  taurus_orbits_flashing_hit:
    score: 70_000 * current_player.pf_multiplier
  logicblock_taurus_orbits_hits_counter_complete:
    knights_defeated_count: 1

event_player:
  logicblock_taurus_orbits_hits_counter_complete: stop_mode_gold_knight_2|500ms

show_player:
  mode_gold_knight_2_started:
    flashing_show:
      show_tokens:
        led: led_gold_knight_2
        color: ffffff