#config_version=6

# All persistent non-wizard configuration :
# - Multiball lock & advancement
# - Wizard mode progression
# - Pop bumpers awards
# - Start/stop handlers dor field mode and mission mode
# -Â Other ?
#   . Cross mission qualifier
#   . Qualifier for extra balls
#   . ...
#
# This is the general mode that underlies non-Wizard-mode gameplay, and handles
# progression tracking for global values like missions, drops, and multiball lights.
#
# This mode does NOT include lights, sounds, and shows for these progressions,
# since active mission modes may overrule them. Instead, those elements are part
# of the Field mode.
#####

mode:
  start_events: start_mode_global
  stop_events: stop_mode_global, ball_will_end
  priority: 300

config:
  # add your configs here. For instance:
  # - global_multiball_madness_light_and_lock.yaml
  # - global_pop_bumpers.yaml
  # - global_wizard_qualifier.yaml

event_player:
  mode_global_started:
    - start_mode_field
    - start_mode_pf_multiplier
    - start_mode_bonus_multiplier
    - start_mode_zodiac_ramps
  mode_global_will_stop:
    - stop_mode_field
    - stop_mode_pf_multiplier
    - stop_mode_bonus_multiplier
    - stop_mode_zodiac_ramps
    - stop_missions
  mode_type_mission_started:
    - stop_mode_field
  mode_type_mission_stopped{not mode["global"].stopping}:
    - start_mode_field
