#config_version=6

# ZODIAC EXTRABALL
# Use the ramps until you spell the ZODIAC word, this activates a light in the lower left to get 1 million.
# Complete again to get 2 millions.
# And so on...
# In the third attempt (18 Ramps) the Extraball light comes.

shots:
  ramp_left_shot:
    switch: s_ramp_left
  ramp_right_shot:
    switch: s_ramp_right
  zodiac_validation_shot:
    switch: s_kickout
    profile: flashing_profile
    enable_events: zodiac_validation
    disable_events: zodiac_validation_shot_flashing_hit
    restart_events: zodiac_validation_shot_flashing_hit
    show_tokens:
      led: led_kickout_jackpot
      color: 0000FF

shot_groups:
  ramp_shot:
    shots: ramp_left_shot, ramp_right_shot

sequences:
  zodiac_sequence:
    persist_state: True
    events:
      - ramp_shot_hit  # Z
      - ramp_shot_hit  # O
      - ramp_shot_hit  # D
      - ramp_shot_hit  # I
      - ramp_shot_hit  # A
      - ramp_shot_hit  # C
    events_when_complete: zodiac_validation
    restart_events: zodiac_validation_shot_flashing_hit

variable_player:
  ramp_shot_hit:
    score: 500 * current_player.pf_multiplier
  zodiac_validation_shot_flashing_hit:
    zodiac_total_count: 1
    zodiac_ball_count: 1
    score: current_player.zodiac_total_count * 1_000_000 * current_player.pf_multiplier

