#config_version=6

player_vars:
  bumpers_score:
    initial_value: 210

  pf_multiplier:
    initial_value: 1

  ramps_combo_score:
    initial_value: 2000
  ramps_combo_count:
    initial_value: 0

  zodiac_total_count:
    initial_value: 0
  zodiac_ball_count:
    initial_value: 0

  bonus_multiplier:
    initial_value: 1

  skillshot_count:
    initial_value: 0

  super_skillshot_count:
    initial_value: 0

  knights_confronted_count:
    initial_value: 0
  knights_defeated_count:
    initial_value: 0
