#config_version=6

lights:
  # Lanes
  led_dragon_lane_left:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_dragon_lane_right:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_outlane_right:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_outlane_left:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_inlane_right:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_inlane_left:
    number:
    platform: virtual
    subtype: led
    type: grb

  led_newton_ball:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_kickout:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_scoop:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_ballsave:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_orbit_left:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_orbit_right:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_ramp_left:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_ramp_right:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_temple:
    number:
    platform: virtual
    subtype: led
    type: grb

  # pf_multiplier
  led_pf_multiplier_x2:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_pf_multiplier_x3:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_pf_multiplier_x4:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_pf_multiplier_x5:
    number:
    platform: virtual
    subtype: led
    type: grb

  # gold knights
  led_gold_knight_1:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_gold_knight_2:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_gold_knight_3:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_gold_knight_4:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_gold_knight_5:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_gold_knight_6:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_gold_knight_7:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_gold_knight_8:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_gold_knight_9:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_gold_knight_10:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_gold_knight_11:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_gold_knight_12:
    number:
    platform: virtual
    subtype: led
    type: grb

  # bronze knights
  led_andromede:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_pegaze:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_dragon:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_cygnus:
    number:
    platform: virtual
    subtype: led
    type: grb


  led_red_target_1:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_red_target_2:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_red_target_3:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_red_target_4:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_red_target_5:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_red_target_6:
    number:
    platform: virtual
    subtype: led
    type: grb