#config_version=6

coils:
  # Flipper Coils
  c_flipper_right_power:
    number: 0-0-1
    default_pulse_ms: 30
    default_recycle: true
    platform_settings:
      recycle_factor: 2
  c_flipper_right_hold:
    number: 0-0-2
    allow_enable: true
  c_flipper_left_power:
    number: 0-0-14
    default_pulse_ms: 30
    default_recycle: true
    platform_settings:
      recycle_factor: 2
  c_flipper_left_hold:
    number: 0-0-13
    allow_enable: true

  c_trough_eject:
    number: 0-0-4
    default_pulse_ms: 10
  c_plunger:
    number: 0-0-0
    default_pulse_ms: 100

  c_slingshot_right:
    number: 0-0-3
    default_pulse_ms: 25
  c_slingshot_left:
    number: 0-0-12
    default_pulse_ms: 25

  c_bumper_left:
    number:
    default_pulse_ms: 50
    platform: virtual
  c_bumper_right:
    number:
    default_pulse_ms: 50
    platform: virtual
  c_bumper_bottom:
    number:
    default_pulse_ms: 50
    platform: virtual

  c_kickback:
    number:
    platform: virtual
  c_scoop:
    number:
    platform: virtual
  c_kickout:
    number:
    platform: virtual

  c_orbit_left_gate:
    number:
    allow_enable: true
    platform: virtual
  c_orbit_right_gate:
    number:
    allow_enable: true
    platform: virtual

autofire_coils:
  slingshot_left:
    coil: c_slingshot_left
    switch: s_slingshot_left
  slingshot_right:
    coil: c_slingshot_right
    switch: s_slingshot_right
  bumper_left:
    coil: c_bumper_left
    switch: s_bumper_left
  bumper_right:
    coil: c_bumper_right
    switch: s_bumper_right
  bumper_bottom:
    coil: c_bumper_bottom
    switch: s_bumper_bottom
