#config_version=6

switches:

  # Cabinet Switches
  s_flipper_left:
    number: 0-0-1
    tags: left_flipper
  s_flipper_right:
    number: 0-0-2
    tags: right_flipper
  s_start:
    number:
    tags: start
    platform: virtual

  # Trough Switches
  s_plunger_lane:
    number: 0-0-9
  s_trough_1:
    number: 1-0-32
    type: NC
  s_trough_2:
    number: 1-0-40
    type: NC
  s_trough_3:
    number: 1-0-48
    type: NC
  s_trough_4:
    number: 1-0-56
    type: NC
  s_trough_5:
    number: 1-0-64
    type: NC
  s_trough_jam:
    number:
    platform: virtual

  # Playfield Switches (autofires coils doesn't have a playfield_active tag)
  s_bumper_left:
    number:
    platform: virtual
    tags: bumpers
  s_bumper_right:
    number:
    platform: virtual
    tags: bumpers
  s_bumper_bottom:
    number:
    platform: virtual
    tags: bumpers
  s_slingshot_left:
    number: 0-0-3
    tags: skillshots
  s_slingshot_right:
    number: 0-0-8
    tags: skillshots
  s_kickout:
    number:
    platform: virtual

  s_orbit_left:
    number:
    tags: playfield_active, orbits
    platform: virtual
  s_orbit_right:
    number:
    tags: playfield_active, orbits
    platform: virtual
  s_spinner_left:
    number:
    tags: playfield_active, spinners
    platform: virtual
  s_spinner_right:
    number:
    tags: playfield_active, spinners
    platform: virtual
  s_ramp_left:
    number:
    tags: playfield_active, ramps
    platform: virtual
  s_ramp_right:
    number:
    tags: playfield_active, ramps
    platform: virtual
  s_temple_out:
    number:
    tags: playfield_active
    platform: virtual
  s_temple_in:
    number:
    platform: virtual

  # Scoop Switches
  s_scoop:
    number:
    platform: virtual

  # Lane Switches
  s_inlane_left:
    number:
    tags: playfield_active, lanes
    platform: virtual
  s_inlane_right:
    number:
    tags: playfield_active, lanes
    platform: virtual
  s_outlane_left:
    number:
    platform: virtual
  s_outlane_right:
    number:
    platform: virtual
  s_dragon_lane_left:
    number:
    tags: playfield_active, lanes, dragon_lanes
    platform: virtual
  s_dragon_lane_right:
    number:
    tags: playfield_active, lanes, dragon_lanes
    platform: virtual

  # Target Switches
  s_newton_ball_target:
    number:
    tags: playfield_active
    platform: virtual
  s_blue_target_left:
    number:
    tags: playfield_active, blue_targets
    platform: virtual
  s_blue_target_right:
    number:
    tags: playfield_active, blue_targets
    platform: virtual
  s_red_target_1:
    number:
    tags: playfield_active, red_targets
    platform: virtual
  s_red_target_2:
    number:
    tags: playfield_active, red_targets
    platform: virtual
  s_red_target_3:
    number:
    tags: playfield_active, red_targets
    platform: virtual
  s_red_target_4:
    number:
    tags: playfield_active, red_targets
    platform: virtual
  s_red_target_5:
    number:
    tags: playfield_active, red_targets
    platform: virtual
  s_red_target_6:
    number:
    tags: playfield_active, red_targets
    platform: virtual
