#config_version=6

lights:
  led_left_lane:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_right_lane:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_newton_ball:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_pf_multiplier_x2:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_pf_multiplier_x3:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_pf_multiplier_x4:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_pf_multiplier_x5:
    number:
    platform: virtual
    subtype: led
    type: grb
