#config_version=6

lights:
  led_dragon_lane_left:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_dragon_lane_right:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_outlane_right:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_outlane_left:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_inlane_right:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_inlane_left:
    number:
    platform: virtual
    subtype: led
    type: grb

  led_newton_ball:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_kickout:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_scoop:
    number:
    platform: virtual
    subtype: led
    type: grb

  led_pf_multiplier_x2:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_pf_multiplier_x3:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_pf_multiplier_x4:
    number:
    platform: virtual
    subtype: led
    type: grb
  led_pf_multiplier_x5:
    number:
    platform: virtual
    subtype: led
    type: grb
