#config_version=6

mode:
  start_events: start_mode_ikki_multiball
  stop_events: stop_mode_ikki_multiball, stop_missions
  events_when_started: mode_type_mission_started
  events_when_stopped: mode_type_mission_stopped

multiballs:
  ikki_multiball:
    ball_count: 3
    ball_locks: bd_lock
    start_events: mode_ikki_multiball_started

event_player:
  multiball_ikki_multiball_ended: stop_mode_ikki_multiball